eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
server:
  port: 1010
spring:
  application:
    name: account-transaction
  datasource:
    password: microservice1453
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: microservice
    driver-class-name: oracle.jdbc.OracleDriver
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    show-sql: true
feign:  hystrix:    enabled: true
ribbon:
  eureka:
    enabled: true
  restclient:
    enabled: true